name: review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  export_otr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install git+https://github.com/OpenPecha/Format-otr.git
    - name: clear review
      run: |
        rm -rf review
    - name: fill in review
      run: |
        from format_otr.export_otr import get_txt
        from format_otr.format_otr import get_format_otr
        import glob
        import os
        if not os.path.exists('./review'):
          os.makedirs('./review')
        for dir in os.listdir('.'):
          if os.path.isdir(dir) and dir != 'review':
            list_of_otr = glob.glob(f'{dir}/*.otr')
            if list_of_otr:
              latest_file = max(list_of_otr, key=os.path.getctime)
              with open(f'review/{dir}.txt', 'w+') as txt_file:
                txt_file.write(get_txt(latest_file))
              with open(f'review/{dir}.otr', 'w+') as otr_file:
                otr_file.write(get_format_otr(latest_file))
      shell: python

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Added or updated review dir